########################### NETWORKS
# There is no need to create any networks outside this docker-compose file.
# Customize the network subnets (192.168.90.0/24 and 91.0/24) below as you please.
# Docker Compose version 3.5 or higher required to define networks this way.

networks:
  t2_proxy:
    external: true
  socket_proxy:
    external: true

##################### SERVICES
services:

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    networks:
      t2_proxy:
      socket_proxy:
    command: -H tcp://socket-proxy:2375
    volumes:
      - ./portainer_data:/data
      # Use Docker Socket Proxy instead for improved security
      # - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    environment:
      - TZ=$TZ
    ports:
      - 9000:9000
      - 9443:9443
